### ISSUE TITLE
Upgrade to Plek 5 blocked by dependency on outdated govuk_publishing_components 17.

### ISSUE THREAD

**Issue by sengi** [alphagov/content-data-admin#1174]
We're currently pinning [a very old version of govuk_publishing_components](https://github.com/alphagov/content-data-admin/blob/bf6b41c/Gemfile#L11) because we're still using a UI component (Accessible Autocomplete) which was removed a long time ago.

This is now blocking updates of other gems: see f15e9fd.

Internal tracking card: https://trello.com/c/egaF1kjo

**Comment by ChrisBAshton** [comment]
We have a [Platform Reliability card](https://trello.com/c/egaF1kjo/2809-replace-accessible-autocomplete-for-content-data-admin) for this 👍

**Comment by sengi** [comment]
Cool, thanks.

**Comment by MuriloDalRi** [comment]
Fixed in https://github.com/alphagov/content-data-admin/pull/1183
